import { defineConfig } from 'wxt';
import { fileURLToPath } from 'node:url';

export default defineConfig({
  alias: {
    '@': fileURLToPath(new URL('./src', import.meta.url)),
  },

  // Content script registration is generated by WXT from entrypoints/content.ts
  // and matches sh.reddit.com + www.reddit.com.
  manifest: {
    name: 'REStore',
    description:
      'Restores the old Reddit look on sh.reddit.com and www.reddit.com.',
    version: '0.3.1',
    permissions: ['storage'],
    host_permissions: ['*://*.reddit.com/*'],
    options_ui: {
      page: 'options.html',
      open_in_tab: true,
    },
  },
});
