import { defineConfig } from 'wxt';
import { fileURLToPath } from 'node:url';

export default defineConfig({
  alias: {
    '@': fileURLToPath(new URL('./src', import.meta.url)),
  },

  // Content script registration is generated by WXT from entrypoints/content.ts
  // and matches only *://sh.reddit.com/*.
  manifest: ({ browser }) => ({
    name: 'REStore',
    description:
      'Restores the old Reddit look on sh.reddit.com, and keeps you on sh.reddit.com only.',
    version: '0.2.2',
    permissions: [
      'storage',
      // Chrome: network-level redirect of www/old/new reddit -> sh.reddit.com
      ...(browser === 'chrome' ? ['declarativeNetRequest', 'webRequest'] : []),
      // Firefox: we redirect from a lightweight listener instead
      ...(browser === 'firefox' ? ['webRequest', 'webRequestBlocking'] : []),
    ],
    host_permissions: ['*://*.reddit.com/*'],
    options_ui: {
      page: 'options.html',
      open_in_tab: true,
    },
  }),
});
